const CONNEXION = "CONNEXION";
const DECONNEXION = "DECONNEXION";
const INSCRIRE = "INSCRIRE";
const GET_SESSION = "GET_SESSION";

const ADD_PRODUCT = "ADD_PRODUCT";
const UPDATE_QUANTITY_PRODUCT = "UPDATE_QUANTITY_PRODUCT";
const REMOVE_PRODUCT = "REMOVE_PRODUCT";
const RESET_BASKET = "RESET_BASKET";

export {
    CONNEXION,
    DECONNEXION,
    INSCRIRE,
    GET_SESSION,

    ADD_PRODUCT,
    UPDATE_QUANTITY_PRODUCT,
    REMOVE_PRODUCT,
    RESET_BASKET
}
